"""Generate deterministic repository statistics in JSON and Markdown."""
from pathlib import Path
import argparse
from olympus_core import ROOT, repository_statistics, write_json

def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=ROOT)
    parser.add_argument("--json", type=Path, default=ROOT / "data/generated/repository-statistics.json")
    parser.add_argument("--markdown", type=Path, default=ROOT / "data/generated/repository-statistics.md")
    args = parser.parse_args()
    stats = repository_statistics(args.root.resolve())
    write_json(args.json, stats)
    rows = "\n".join(f"| {key.replace('_', ' ').title()} | {value} |" for key, value in stats.items())
    args.markdown.parent.mkdir(parents=True, exist_ok=True)
    args.markdown.write_text(
        "---\nid: GENERATED-REPOSITORY-STATISTICS\ntitle: \"Repository Statistics\"\n"
        "type: generated-report\nstatus: generated\nversion: 1.1.0\nowner: automation\n---\n\n"
        "# Repository Statistics\n\n"
        "> Generated by `scripts/generate_statistics.py`; do not edit manually.\n\n"
        "## Metrics\n\n| Metric | Value |\n|---|---|\n" + rows + "\n",
        encoding="utf-8",
        newline="\n",
    )
    print(f"Wrote {args.json} and {args.markdown}")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
