"""Generate repository validation and health reports."""
from pathlib import Path
import argparse
from datetime import datetime, timezone
from olympus_core import ROOT, repository_statistics, validate_repository, write_json

def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=ROOT)
    parser.add_argument("--json", type=Path, default=ROOT / "data/generated/repository-health.json")
    parser.add_argument("--markdown", type=Path, default=ROOT / "data/generated/repository-health.md")
    parser.add_argument("--trend", type=Path, default=ROOT / "data/generated/repository-trend.md")
    args = parser.parse_args()
    previous = {}
    if args.json.exists():
        try:
            import json
            previous = json.loads(args.json.read_text(encoding="utf-8")).get("statistics", {})
        except (ValueError, OSError):
            previous = {}
    results = validate_repository(args.root.resolve())
    statistics = repository_statistics(args.root.resolve())
    trend_keys = ("markdown_files", "word_count", "tables", "mermaid_diagrams", "markdown_links")
    trend = {key: int(statistics.get(key, 0)) - int(previous.get(key, statistics.get(key, 0))) for key in trend_keys}
    payload = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "status": "healthy" if all(result.passed for result in results) else "unhealthy",
        "statistics": statistics,
        "trend_from_previous_generation": trend,
        "checks": [result.serializable() for result in results],
    }
    write_json(args.json, payload)
    rows = "\n".join(
        f"| {result.name} | {'PASS' if result.passed else 'FAIL'} | "
        f"{sum(i.severity == 'error' for i in result.issues)} | "
        f"{sum(i.severity == 'warning' for i in result.issues)} |"
        for result in results
    )
    args.markdown.parent.mkdir(parents=True, exist_ok=True)
    args.markdown.write_text(
        "---\nid: GENERATED-REPOSITORY-HEALTH\ntitle: \"Repository Health\"\n"
        "type: generated-report\nstatus: generated\nversion: 1.1.0\nowner: automation\n---\n\n"
        "# Repository Health\n\n"
        "> Generated by `scripts/repository_health.py`; do not edit manually.\n\n"
        f"## Status\n\n**{payload['status'].upper()}**\n\n"
        "## Validation Dashboard\n\n| Check | Status | Errors | Warnings |\n|---|---:|---:|---:|\n"
        + rows
        + "\n\n## Coverage Dashboard\n\n"
        f"- Approved, active, complete, released, generated, or example coverage: "
        f"**{statistics['completion_percentage']}%**.\n"
        f"- Planned Markdown artifacts: **{statistics['planned']}**.\n"
        "\n## Repository Metrics Dashboard\n\n"
        f"- Markdown files: **{statistics['markdown_files']}**.\n"
        f"- Words: **{statistics['word_count']}**.\n"
        f"- Mermaid diagrams: **{statistics['mermaid_diagrams']}**.\n"
        f"- Markdown links: **{statistics['markdown_links']}**.\n"
        "\n## Technical Debt Dashboard\n\n"
        "- External-link reachability remains a scheduled network check.\n"
        "- Mermaid compilation requires the documentation dependency set.\n"
        "- Planned curriculum scaffolds remain outside Module 01 completion.\n",
        encoding="utf-8",
        newline="\n",
    )
    trend_rows = "\n".join(f"| {key.replace('_', ' ').title()} | {statistics[key]} | {trend[key]:+d} |" for key in trend_keys)
    args.trend.write_text(
        "---\nid: GENERATED-REPOSITORY-TREND\ntitle: \"Repository Trend\"\n"
        "type: generated-report\nstatus: generated\nversion: 1.1.0\nowner: automation\n---\n\n"
        "# Repository Trend\n\n"
        "> Generated by `scripts/repository_health.py`; deltas compare the prior generated health snapshot.\n\n"
        "## Trend Report\n\n| Metric | Current | Delta |\n|---|---:|---:|\n"
        + trend_rows + "\n",
        encoding="utf-8",
        newline="\n",
    )
    print(f"Repository status: {payload['status']}")
    return 0 if payload["status"] == "healthy" else 1

if __name__ == "__main__":
    raise SystemExit(main())
